<a href="https://colab.research.google.com/github/joanby/tensorflow2/blob/master/Colab%202%20-%20Introducción%20a%20TensorFlow%202.0%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 2

### Instalar TensorFlow 2

In [1]:
!pip install -U "tensorflow==2.20.0"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 620.7/620.7 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 106.1 MB/s eta 0:00:00
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.19.0
    Uninstalling tensorboard-2.19.0:
      Successfully uninstalled tensorboard-2.19.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.19.0
    Uninstalling tensorflow-2.19.0:
      Successfully uninstalled tensorflow-2.19.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.19.0 requires tensorflow<2.20,>=2.19, but you have tensorflow 2.20.0 which is incompatible.
tensorflow-text 2.19.0 requires tensorflow<2.20,>=2.19.0, but you have tensorflow 2.20.0 which is incompatible.
tensorflow-decision-forests 1.12.0 requires tensorflow==2.19.0, but you have tensorflow 2.20.0 which is in

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.20.0'

### Constantes

#### Definir una constante

In [4]:
# Definir una constante en TensorFlow 2
tensor_2 = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
# Obtener el tamaño de un tensor
tensor_2.shape

TensorShape([2, 2])

#### Consultar los valores de una constante

In [7]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy, sin necesidad de una session como en TensorFlow 1
tensor_2.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [8]:
# Podemos convertir un array de numpy a un tensor de TensorFlow directamente
numpy_tensor = np.array([[23,  4], [32, 51]])

In [9]:
# Ahora ese array lo convertiremos en tensor como constante pasandole el propio numpy_tensor
tensor_from_numpy = tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

#### Definir una variable

In [11]:
# Para crear una variable la debemos invocar con tf.Variable
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Consultar los valores de una variable

In [12]:
# Para consultar los valores de una variable utilizamos numpy()
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Cambiar un valor especifico de una variable

In [13]:
# Para cambiar el valor a una variable le debemos indicar a que fila y columna [0, 2] y con .assing le indicamos el nuevo valor (100)
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [14]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operaciones con tensores

In [15]:
# Creamos un tensor constante con dos filas y dos columnas
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Sumar un escalar a un tensor

In [16]:
# Le sumamos un 2 a cada una
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicar un escalar por un tensor

In [17]:
# Lo mismo con la multiplicacion
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Utilizar funciones de Numpy sobre tensores de TensorFlow

In [18]:
# Obtener los cuadrados de todos los números de un tensor de TensorFlow
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [19]:
# Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Producto escalar entre dos tensores

In [21]:
# tensor = [[1, 2],[3, 4]] y tensor_2 = [[23,  4],[32, 51]]
# La operacion hace 1*23 + 2*32 = 87, 1*4 + 2*51 = 106....
np.dot(tensor, tensor_2)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings en TensorFlow 2

In [22]:
# Para crear un String se utiliza la funcion constant de tensorflow
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operaciones simples con strings

In [23]:
# Para obtener la longitud del String (cantidad de caracteres)
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [24]:
# Tambien podemos codificar o descodificar, transformaremos de texto a UTF8, nos devolvera los 10 caracteres en formato UTF8
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Almacenar arrays de strings

In [25]:
# Tamien podemos tener Arrays de String, pasandole con [] entre "" separados por ,
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [26]:
# Iterar sobre un array de strings en TF
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
